### ISSUE TITLE
Why base install instruction on https://github.com/artnie/knowrob

### ISSUE THREAD

**Issue by chcorbato** [estherag/knowrob-intro#1]
Why not use the upstream repo https://github.com/knowrob/knowrob ?
Forn example with the installation instruction for MongoDB and SWI-Prolog
https://github.com/knowrob/knowrob#installation-of-swi-prolog-and-mongodb

**Comment by estherag** [comment]
I think it's the same. From Knowrob docummentation:

Prerequisites
ROS (ROS melodic for the master branch)
SWI Prolog >= 8.2.4 (see [Further Information](https://github.com/artnie/knowrob/tree/update-setup#further-information))
mongo DB server >= 4.4 and libmongoc (see [Further Information](https://github.com/artnie/knowrob/tree/update-setup#further-information))
[rosprolog](https://github.com/knowrob/rosprolog)

That's the link available in further information for mongo DB and SWI prolog. Apparently, the only change is the Mongo DB version (more updated in knowrob repo, so I will change the link to the one you are suggesting)
